# Generated by Django 5.2.6 on 2025-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_is_revoked'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
