# Generated by Django 5.2.6 on 2025-10-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificate_certificate_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='blockchain_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='blockchain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revocation_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
